name: Build (Make)
on:
    workflow_dispatch:
    pull_request:

jobs:
    compile:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install typescript
              run: sudo apt install -y node-typescript make
            - run: make compile
