name: Lint
on:
  workflow_dispatch:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Run prettier
        run: npx prettier . --check